USE angaadi;

CREATE USER IF NOT EXISTS 'public_access' IDENTIFIED BY '0000';
CREATE USER IF NOT EXISTS 'staff' IDENTIFIED BY '1111';
CREATE USER IF NOT EXISTS 'courier_side' IDENTIFIED BY '2222';


GRANT SELECT,INSERT,DELETE,UPDATE ON cart TO public_access;
GRANT SELECT,INSERT,DELETE,UPDATE ON customer TO public_access;
GRANT SELECT,INSERT,DELETE,UPDATE ON guest TO public_access;
GRANT SELECT,INSERT,DELETE,UPDATE ON orders TO public_access;
GRANT SELECT,INSERT,DELETE,UPDATE ON payment TO public_access;
GRANT SELECT,INSERT,DELETE,UPDATE ON shipping_address TO public_access;

GRANT SELECT,INSERT,DELETE,UPDATE ON *.* TO staff;

GRANT SELECT,INSERT,UPDATE ON freight_details TO courier_side;
GRANT SELECT,UPDATE ON orders TO courier_side;




